# Generated by Django 4.0.4 on 2022-04-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schedule',
            new_name='Schedules',
        ),
    ]
