# Generated by Django 4.0.4 on 2022-04-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicate', '0002_rename_schedule_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
